### ISSUE TITLE
微博用户关注的人只能看前140位

### ISSUE THREAD

**Issue by hui99995** [Artificialimbecile/WeiboSpider#1]
应该是api显示的，所有显示不全 分析的不会准的

**Comment by Artificialimbecile** [comment]
weibo.py是用的api，weibo_follow.py是爬取的页面

**Comment by hui99995** [comment]
那draw.py分析的关系图不全，因为关注的用户都不能爬全。

**Comment by Artificialimbecile** [comment]
draw.py使用的是weibo_follow.py，可以爬全

**Comment by Artificialimbecile** [comment]
weibo_follow.py不是用的api，是爬取的页面，能够爬取全部关注用户，而且删除了大V和粉丝数大于1000的用户，分析会更准确

**Comment by hui99995** [comment]
是不是要关注对方才能看全？

在2019年12月17日星期二，Siwuxie <notifications@github.com>认为：

**Comment by Artificialimbecile** [comment]
确实如此，关注对方且对方不是大V用户才能看到全部关注列表，未关注对方或者对方是大V用户，只能看到关注列表前20页，这应该是微博系统限制，我才发现，谢谢提醒。

**Comment by hui99995** [comment]
所以这个关系分析不完整，我可以关注我想分析的用户，但我没法做到去把我需要分析的用户的关注对象全部关注一遍。

Siwuxie <notifications@github.com> 于2019年12月17日周二 下午9:00写道：

**Comment by Artificialimbecile** [comment]
有什么好的方法吗，我发现各个版本的微博网站都有限制

**Comment by hui99995** [comment]
有一个办法，我尝试在微博客户端上看未关注的用户的关注对象，是可以看到全部的，那就代表只要拿到客户端的api就可以看到未关注用户的所有关注对象，可以尝试抓包获取客户端的api，要是你成功了告诉我一声。

发自我的iPad

**Comment by Artificialimbecile** [comment]
你说的客户端是指手机app吗，手机app也只能看到前200个关注对象，与https://weibo.cn/看到列表是一样的，而且我发现不是关注对方就能看到全部列表，必须是双方互相关注才可以。

**Comment by hui99995** [comment]
试了下还真是 那目前就没有好的解决方法了。

发自我的iPad
